theme: jekyll-theme-hacker

title: "j3colorstretch"
description: Stretches astronomical images while preserving the colors.

google_analytics: UA-177272533-1

include: doc, doc/_static, doc/_source

plugins:
  - jekyll-seo-tag
