#!/usr/bin/env bash

# Copyright(c) 2020 Joachim Janz. All rights reserved,
#   inspired by a suggestion of Khalid Baheyeldin.

if [ "$#" -le 2 ] || ! [ -d "$1" ]; then
    echo
    echo "Usage: batch-stretch dir ext (tif or jpg) [dcraw] [j3colorstretch parameters]"
    echo
    echo "  This script runs j3colorstretch with the provided optional parameters on all"
    echo "  images in the directory dir with the extension ext. The output can be either"
    echo "  in tif (16bit) or jpg. Optionally dcraw can be run before, e.g. to convert"
    echo "  raw data to the tif file format, which can be processed by j3colorstretch."
    echo
    exit 1
fi

DIR="$1"
EXT="$2"
EXT_OUT="$3"
shift
shift
shift

dcraw=false
if [[ $1 == "dcraw" ]]; then
    shift
    dcraw=true
    temp_dir=`mktemp -d` 
fi

found_no_file=true

while read -r -d $'\0' file; do 
  found_no_file=false
  filename=$(basename -- "$file")
  extension="${filename##*.}"
  filename="${filename%.*}"

  if [ "$dcraw" = true ] ; then
    echo dcraw -4 -T -c "${file} -x > ${temp_dir}/${filename}_j3cs.tiff"
    echo j3colorstretch "${temp_dir}/${filename}_j3cs.tiff ${@}" -x --output="${DIR}/${filename}_j3cs.${EXT_OUT} ${@}"
  else
    echo j3colorstretch "${file}" -x --output="${DIR}/${filename}_j3cs.${EXT_OUT} ${@}"
  fi
done < <(find "$DIR" -maxdepth 1 \( -iname \*.${EXT} \) -print0)

if [ "$dcraw" = true ] ; then
    rm -rf ${temp_dir}
fi

if [ "$found_no_file" = true ] ; then
    echo "  Found no .${EXT} files in ${DIR}"
fi